### ISSUE TITLE
Wont Install - unRAID Docker

### ISSUE THREAD

**Issue by hernandito** [coolasice1999/tmmcliv4#1] opened 2023-12-09 16:54 UTC
Hello,

I have been using your TMM-CLI-Crontab Docker for some years now as part of my workflow. This is the TMM v.3.x version. I use by creating a template for Dockers running in my unRAID server.

I have tried creating a template for the **TMM-CLI version 4**. It doesn't work. I have studied your Docker file and I believe everything runs OK... it downloads the tmm.tar.gz file to the /defaults folder. But I don't think it installs or extracts the downloaded file.

When I go to the /config folder, it is empty. So when the entrypoint.sh runs, I get an error:

`chmod: cannot access '/config/*': No such file or directory`

The container is running, but TMM is not there. Being in the CLI it does not run when I type **tinyMediaManager**

I am hoping this is something with a simple solution. I have tried everything I can.

Please advise.... thank you very much for the TMMCLI v.3.

**Comment by coolasice1999** [comment] 2023-12-11 14:38
I had to update to debian due to limits in alpine and the new version of tmm.   The init.d isn't working on startup as I am not fluent in the newer debian system.  I am working on a simple fix, stand by.

**Comment by coolasice1999** [comment] 2023-12-11 15:05
Should be fixed, give it a try

**Comment by coolasice1999** [comment] 2023-12-11 15:23
should be working now, please try

**Comment by hernandito** [comment] 2023-12-12 13:49
Thank you! I am having a power supply issue w/ my server... It will take me a few days to correct. I will try it out once I get it back up.

Thank you again,

H.

**Comment by hernandito** [comment] 2023-12-12 13:58
One item I had noted in previous version was that the script calls to copy and untar the downloaded file into the /config folder. 

I noticed that after extracting it, it placed the contents of the tar file in /config/tmm?? (can't recall exact name). Basically it was not in the root of /config. 

I am not sure if this had anything to do with the error.

Thanks

**Comment by coolasice1999** [comment] 2023-12-12 16:40
folder extraction was not the cause, but has also been corrected

**Comment by hernandito** [comment] 2023-12-16 15:10
Hi... I am hoping my server issues are resolved. I gave the update a try and:

When starting the container I get:
`chown: invalid spec: '0:'`

The contents of the /config folder seem to have all the proper files. but, as a test, if I console into the container, and type:
     ` tinyMediaManager -V` 
I get a command not found. I am not sure if the chown has anything to do with the issue. I am following the TMM guide shown on TMMCLI's [page here.](https://www.tinymediamanager.org/docs/commandline#tinymediamanager-v3) 

Not sure if I am doing anything wrong....

Thank you!

**Comment by coolasice1999** [comment] 2023-12-17 01:19
your template is incorrectly setup in unraid,  make sure your template xml file is setup as follows:
![tmm temp](https://github.com/coolasice1999/tmmcliv4/assets/52601736/7200c08f-3789-45ea-a3fe-3d4f64a38b15)

**Comment by hernandito** [comment] 2023-12-17 04:15
Thank you... I got it to work....!! 

However, I cant recall the steps I took to make v.3 work. Things like media location folders, kodi URL/password, Scraper API's, etc. I will dive into it and see if I can figure out again. I seem  to recall using the GUI interface... but not sure.

Thank you again!

H.

**Comment by hernandito** [comment] 2023-12-17 04:32
From the version 3 /config I copied the entire contents of the /cache and /data sub folders... it seems to be working! Still not a solution with starting this from scratch.

I see you use unRAID! Have you thought of creating a template and have it show up in CA?

**Comment by coolasice1999** [comment] 2023-12-17 15:27
I originally created these dockers for my personal use by cloning others work and adding the cron timing for auto updates overnight when new media was downloaded.  I don't have lots of time to keep updating and adding features for others so I don't broadcast them.  If others want to use them they are there to use but i can't always provide support for them.

for configuring and setup, i used the gui version as my gui and cli both share the same config/database/media files

**Closed as completed** 2024-05-18 02:45 UTC
